codecov:
  branch: master

coverage:
  precision: 2
  round: nearest
  range: 70...100
  ignore:
    - Samples/*
    - Pods/*
    - Vendor/*

  status:
    project: true
    patch: true
    changes: false

comment:
  layout: "header, diff, changes"
  behavior: default
  branches: master
