codecov:
    strict_yaml_branch: master

coverage:
  precision: 2
  round: nearest
  range: 70...100
  ignore:
    - "Vendor/"
    - "Samples/"

  status:
    project: true
    patch: true
    changes: false

comment:
  layout: "header, diff, tree, changes"
  behavior: default
  branches: master
