codecov:
    token: 26948af5-4e6a-4fb3-9b6d-abc51cb8c2ad

coverage:
  precision: 2
  round: nearest
  range: 80...100
  ignore:
    - Samples/
    - Vendor/

  status:
    project: true
    patch: true
    changes: true

comment:
  layout: "header, diff, tree, changes"
  behavior: default
  branches: master
