disabled_rules:
    - line_length
    - file_length
    - function_body_length
    - type_body_length
    - trailing_whitespace
    - cyclomatic_complexity

included:
    # When called from Xcode Project
    - iOS
    - tvOS
    - Tests
    - watchOS
    - watchOS Extension
    - ../Source

    # When called by Danger
    - Samples
    - Source

excluded:
    # When called from Xcode Project
    - ../Vendor

    # When called by Danger
    - */SwiftGen/*

reporter: "xcode"
