osx_image: xcode8
language: objective-c
sudo: false

before_install:
    - gem install bundler -v 1.9.10 --quiet
    - gem install cocoapods -v '1.0.1' --no-rdoc --no-ri --no-document --quiet
    - bundle exec danger

script:
    - git submodule update --init --recursive
    - sh Installer.sh 'Fonts/FontAwesome-4.6.3/FontAwesome.otf'
    - cd Samples && pod deintegrate && pod install

env:
    global:
    - LANG=en_US.UTF-8

    - WORKSPACE="Samples.xcworkspace"
    - IOS_SCHEME="iOS-Sample"
    - IOS_SDK="iphonesimulator10.0"

    matrix:
    - DESTINATION="OS=10.0,name=iPhone 6s" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME"

script:
    - xcodebuild clean build test -scheme "$SCHEME" -workspace "$WORKSPACE" SDK="$IOS_SDK" -destination "$DESTINATION" -configuration Debug  GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES;

after_success:
    - bash <(curl -s https://codecov.io/bash)
