osx_image: xcode7.3
language: objective-c

cache:
- bundler
- cocoapods

before_install:
- bundle install
- cd Samples && pod install

script:
- xcodebuild clean build test -scheme iOS-Sample -workspace Samples.xcworkspace -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3'